### ISSUE TITLE
💡 [REQUEST] - Expected step failure 

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#186]
### Summary

We've been asked to consider writing functionality that provides an "optional" fail for a step. By doing this, we can have a cleanup step that fails and still run the rest of the steps.

The default behavior will stay as "fail loudly."

### Basic Example

```yaml
- name: cleanup
   ignore_errors: true
   inline: ...
```
