### ISSUE TITLE
CLI `-v` arg changes state of config file

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#3]
`.config.yaml` prior to running the forge:

```yaml
inventory:
    - ~/pt/tools/TTP-Runner/ttps
    logfile: ""
    nocolor: false
    stacktrace: false
    verbose: false
```

Run forge without verbose option:

```bash
go build -o forge

./forge -c .config.yaml run ttps/privilege-escalation/credential-theft/hello-world/ttp.yaml
```

`.config.yaml` after running the forge:

```yaml
inventory:
    - ~/pt/tools/TTP-Runner/ttps
    logfile: ""
    nocolor: false
    stacktrace: false
    verbose: false
```

Run forge with verbose option:

```bash
./forge -v -c .config.yaml run ttps/privilege-escalation/credential-theft/hello-world/ttp.yaml
```

`.config.yaml` after running the forge with verbose set:

```yaml
inventory:
    - ~/pt/tools/TTP-Runner/ttps
    logfile: ""
    nocolor: false
    stacktrace: false
    verbose: true
```
