### ISSUE TITLE
Viper creates improperly formatted YAML

### ISSUE THREAD

**Issue by l50** [facebookincubator/TTPForge#4]
Properly formatted config:

```yaml
---
inventory:
  - ~/pt/tools/TTP-Runner/ttps
logfile: ""
nocolor: false
stacktrace: false
verbose: false
```

After Viper writes it out:

```yaml
inventory:
    - ~/pt/tools/TTP-Runner/ttps
logfile: ""
nocolor: false
stacktrace: false
verbose: false
```
