### ISSUE TITLE
💡 [REQUEST] - Add `append` and `delete` fields to edit_step 

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#412]
### Summary

Add support for the following fields to [EditStep](https://github.com/facebookincubator/TTPForge/blob/15eca51393a51ff141dfeb6cff08b2f1f0cde98d/pkg/blocks/editstep.go#L39): 

`append: [string]` -  should append the desired string to the end of the file 
`delete: [string]` - should delete the desired string from the file wherever it occurs

The following conditions should be enforced:

* specifying `old`, `new`, or `regexp` in conjunction with `append` should yield an error - those aren't valid combinations 
* specifying `old` or `new` with `delete` should result in an error, same reason 
* `delete` and `regexp` should work together - lines matching the regexp should be deleted 

Corresponding test cases should be added here (the tests are useful examples to look at as well): 

https://github.com/facebookincubator/TTPForge/blob/15eca51393a51ff141dfeb6cff08b2f1f0cde98d/pkg/blocks/editstep_test.go 

### Basic Example

This should append `bar` to `foo`

```
name: append-example
description: wut
steps:
  - name: make-foo
    create_file: /tmp/foo 
  - name: append-bar
    edit_file: /tmp/foo 
      edits:
        - append: bar
  - name: cat-foo
    inline:  cat /tmp/foo
```

This should then delete `bar` from that same file:

```
name: delete-example
description: wut
steps:
  - name: append-bar
    edit_file: /tmp/foo 
      edits:
        - delete: foo
```

### Drawbacks

 `EditStep` will be trending toward having too many fields, but it's better than having separate `append_file` and `delete_from_file` steps I think - these thematically fit under `edit_file` quite nicely
