### ISSUE TITLE
💡 [REQUEST] - Regexp Support in Argument Parsing 

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#413]
### Summary

We need the ability to write argument specifications like this:

```
name: foo-ttp
description: bar 
args:
  - name: ec2_instance_id
     # this may not be the correct regexp format for Golang's regexp library, plz forgive my rush 🙏 
     regexp: "^i-[a-fA-F0-9]{17}$" 
steps: 
 ....
```

The following conditions should be enforced:

* an error should be thrown if `regexp:` is specified for a non-string argument type 
* if the user passes an argument value that does not match the regexp, an error should be thrown

Right now, folks writing TTPs need to hack around this in bash - see e.g. 

https://github.com/facebookincubator/ForgeArmory/pull/86/files#diff-b801212aaa7b44cd8313fe6739e594ee04eb0cd773eb32bf726910ae069ededaR58 

For implementation guidance, check out this recent PR:

https://github.com/facebookincubator/TTPForge/pull/411

### Basic Example

See above

### Drawbacks

I think this is relatively free from drawbacks, although we'll want to keep an eye on basic, commonly-used regular expressions and import them as new strong argument types, e.g. `type: url` would be a good candidate
