### ISSUE TITLE
💡 [REQUEST] - Add sprig support to TTPForge Template Rendering 

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#419]
### Summary

TTPForge YAML files are actually all templates powered by the [text/template](https://pkg.go.dev/text/template) package. 

This powers our usage of command line arguments by rendering template variable references such as `{{.Args.foo}}` 

We could do much more with templating if we add support for the Sprig library of template functions (this is used by Helm, a similar yaml-based tool that is very popular in the kubernetes community) 

https://masterminds.github.io/sprig/
https://github.com/Masterminds/sprig 

Examples of what we could do:

* Use sprig's  `randAlphaNum` to support adding a random suffix to strings used in our TTPs 
* Generate UUIDs without relying on external shell commands (using `uuidv4` function)
* Use `expandenv` to reference environment variables in non-shell steps like `create_file`  

The template rendering code that you will need to modify lives here:

https://github.com/facebookincubator/TTPForge/blob/89d43303661b0a2540b828aa920458f796f2a039/pkg/blocks/loader.go#L51C1-L51C1

### Basic Example

I would love for something like this to work:

```
name: write-evil-sudoers-file 
description: writes a malicious sudoers file to /etc/sudoers.d/[YOUR_FILE_NAME]
args:
  - name: file_name
    description: name of sudoers file to create under /etc/sudoers.d
    default: evil
steps:
  - name: write-evil-sudoers-file
    create_file:  /etc/sudoers.d/{{.Args.file_name}} 
    contents: | 
      {{expandenv USER}} ALL=(ALL:ALL) ALL 
```

### Drawbacks

None that I'm aware of - Sprig is widely used and should be a valuable addition
