### ISSUE TITLE
💡 [REQUEST] -  Support for Command-Line Arguments  

### ISSUE THREAD

**Issue by d3sch41n** [facebookincubator/TTPForge#49]
### Summary

We need the ability to pass input arguments to yaml TTPs. 

Our yaml format should support command line arguments similar to the `input_arguments` 
block used by atomic red team (ART) ([example](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.002/T1003.002.yaml#L66)):

```
  input_arguments:
    file_path:
      description: Path to the file to copy
      type: path
      default: '%SystemRoot%/system32/config/SAM'
    file_name:
      description: Name of the copied file
      type: string
      default: SAM
    copy_dest:
      description: Destination of the copied file
      type: string
      default: '%temp%'
```
The input arguments for ART are provided upon invocation:

https://github.com/redcanaryco/invoke-atomicredteam/wiki/Specify-Custom-Input-Arguments

### Basic Example

We could have a top-level yaml field:

```
arguments:
  - name: foo
    description: bar
    type: int
```

Validation like `type:` etc could be added later - the top priority thing is to support
referencing these vars within inline blocks: 

```
inline: |
    cp ${args.foo} /wut
```

     

### Drawbacks

We presently can achieve this behavior by setting environment variables which are correctly expanded
when referenced inside of `inline:` blocks - therefore, this feature is not strictly necessary in order to support
the incorporation of user-specified values into TTP execution. 

 

### Unresolved questions

Should we prefix arg variables as shown below to distinguish them from environment variables?

```
inline: |
    cp ${args.foo} /wut
```
